### ISSUE TITLE
File-names with dots in can't be transformed

### ISSUE THREAD

**Issue by Amethi** [sayedihashimi/slow-cheetah#134]
Files with a dot (period) in don't get the transform option when you right-click on them. This is a show-stopper for me as all our config files have dots in them. Doh. Apologies if this has already been raised.

I'm using the latest version of the plugin and VS2013 Pro and the project is targeting Framework 4.5.1.

**Comment by davilimap** [comment]
If your issue is say, having a file called `App.system.config`, transforms are available for this file and the menu should be showing correctly. The transformation for this file would be called `App.system.Debug.config` and transform on build correctly as well.
If ater updating the problem persists, reopen the issue.
