### ISSUE TITLE
Windows store /universal app localsettings.config or app.config not deployed

### ISSUE THREAD

**Issue by olivierpierrat** [sayedihashimi/slow-cheetah#180]
Hi all, 

I use SlowCheetah 2.5.15 with VS2015 to manage an app.config file for a Win8.1 universal app in order to manage connectionStrings based on build config. Everything is ok about the transformation but at the deploy stage the wrong file is publish to the ..\AppX\ folder - i.e. the default app.config (with no transformation) is published ! Does anyone have a solution. 

It seems that the target _ComputeAppxPackagePayload building _UnfilteredAppxPackagePayload and _CalculateInputsForGenerateAppxPackageRecipe list building _GenerateAppxPackageRecipeInput list contains the wrong file. This lead to have a HelloWorld.build.appxrecipe (my app is HelloWorld) with the wrong file - i.e. the app.config with non transformation ! 

Thx for your help. Let me know if you need the complete build log or HelloWorld.build.appxrecipe file.

**Comment by sayedihashimi** [comment]
@olivierpierrat SlowCheetah uses the prescribed mechanism to update `app.config` on build. It's similar to how the BCL nuget package transforms `app.config` on build. To me this sounds like a bug in the universal app project type. I'd recommend opening a Microsoft connect bug or creating a new item on uservoice for Visual Studio.

If it is an issue that would require new development in SlowCheetah to support the new project type, I won't be able to implement it that since I've [moved on](https://github.com/sayedihashimi/slow-cheetah/issues/158). @WillBuik is the new owner, he will have to decide if the new feature will be added.

**Comment by olivierpierrat** [comment]
Thanks for your answer. It seems effectively after deeper investigations that the task that build the list of file that should be included in the package is wrong, but that's a VS problem.

**Comment by sayedihashimi** [comment]
@olivierpierrat ok closing
