### ISSUE TITLE
SlowCheetah transformation creates rogue folder

### ISSUE THREAD

**Issue by benrogers1967** [sayedihashimi/slow-cheetah#69]
Hi,
I am using SlowCheetah version 2.5.3. The transformations are all working well but a strange folder is created. I created a baby test solution to demonstrate the problem. 

The test solution is a Console Application called SlowCheetahPlay. It has three config files. There is the App.config file and two others. One of them is in a folder called Configuration. Please see picture of Solution Explorer

![SlowCheetahPlaySolutionExplorer](https://f.cloud.github.com/assets/1154435/155326/8efbc24c-7643-11e2-9cc2-9bbfb799a7e9.PNG)

The Transformations all work correctly for the Release build but a strange folder is created. Please see picture with highlight .

![SlowCheetahPlayReleaseFolder](https://f.cloud.github.com/assets/1154435/155347/f2fe5f84-7643-11e2-9db7-486cc89a5301.PNG)

The strange folder is called Another.config;Configuration

Thank you,

Regards Ben

**Comment by davilimap** [comment]
This seems to be fixed with the latest version. I downloaded the sample project (deleted the already populated `bin\release` folder) and on build the transformation seems to be working. If this is still a problem, reopen the issue with more details.
As for @khawajaumarfarooq's issue, that's actually #82 which will be looked into.
